from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage

chat_template = ChatPromptTemplate(
    [
        ("system", "You are a helpful assistent"),
        (MessagesPlaceholder(variable_name="chat_history")),
        ("human", "{query}"),
    ]
)

chat_history = [
    HumanMessage(
        content="Tell me about the Earth.", additional_kwargs={}, response_metadata={}
    ),
    AIMessage(
        content="Okay, here's a rundown of some key facts about our home, Earth:\n\n**Basic Facts:**\n\n*   **Name:** Earth (The name comes from the Old English words 'eorþe' and 'erda', meaning ground or soil). It's the only planet not named after a Greco-Roman deity.\n*   **Planet Type:** Terrestrial (rocky planet)\n*   **Diameter:** Approximately 12,742 kilometers (7,918 miles)\n*   **Circumference:** Approximately 40,075 kilometers (24,901 miles)\n*   **Mass:** 5.97 x 10^24 kg\n*   **Density:** 5.514 g/cm³ (the densest planet in our solar system)\n*   **Orbit:** It orbits the Sun at an average distance of about 149.6 million kilometers (93 million miles). This distance is defined as one Astronomical Unit (AU).\n*   **Orbit Time (Year):** 365.25 days (This is why we have leap years!)\n*   **Rotation Time (Day):** 23 hours, 56 minutes, and 4 seconds\n*   **Axial Tilt:** 23.5 degrees (This tilt is responsible for our seasons)\n*   **Atmosphere:** Primarily composed of nitrogen (about 78%) and oxygen (about 21%), with small amounts of other gases like argon, carbon dioxide, and trace gases.\n*   **Moons:** One natural satellite: The Moon (Luna).\n*   **Rings:** None\n\n**Key Features and Characteristics:**\n\n*   **Life:** Earth is the only known planet to harbor life. It has a vast and diverse biosphere, ranging from microscopic organisms to complex plants and animals.\n*   **Water:** Earth is often called the \"Blue Planet\" because about 71% of its surface is covered by water in the form of oceans, lakes, rivers, and ice. Liquid water is essential for life as we know it.\n*   **Plate Tectonics:** Earth's outer layer is divided into several large and small plates that slowly move and interact. This process, called plate tectonics, causes earthquakes, volcanoes, and the formation of mountains.\n*   **Magnetic Field:** Earth has a strong magnetic field generated by the movement of molten iron in its outer core. This magnetic field protects us from harmful solar wind and cosmic radiation.\n*   **Atmosphere:** The atmosphere protects us from harmful radiation from the sun and helps regulate the planet's temperature.\n*   **Structure:** Earth has a layered structure:\n    *   **Crust:** The outermost solid layer (oceanic and continental).\n    *   **Mantle:** A thick, mostly solid layer beneath the crust.\n    *   **Outer Core:** A liquid layer composed mainly of iron and nickel.\n    *   **Inner Core:** A solid, dense sphere of iron and nickel.\n*   **Seasons:** Earth experiences seasons due to its axial tilt. As the Earth orbits the Sun, different parts of the planet are tilted towards the Sun, resulting in variations in sunlight and temperature.\n*   **Unique Atmosphere:** Earth's atmosphere is unique because it contains a significant amount of free oxygen, which is a byproduct of photosynthesis by plants and other organisms.\n\n**Position in the Solar System:**\n\n*   Earth is the third planet from the Sun.\n*   It is located between Venus and Mars.\n*   It is the largest of the four terrestrial planets in our solar system.\n\n**Interesting Facts:**\n\n*   Earth is not perfectly spherical; it's slightly flattened at the poles and bulging at the equator, forming an oblate spheroid.\n*   The highest point on Earth is Mount Everest, and the lowest point is the Mariana Trench.\n*   The Earth is constantly changing due to geological activity, erosion, and the impact of living organisms.\n*   The Earth's rotation is gradually slowing down, which means that days were shorter in the past.\n\n**In summary, Earth is a dynamic and unique planet with a complex system of interacting components that make it habitable for life. It's a truly special place in our solar system and the only home we know!**\n\nDo you have any specific questions about Earth that you'd like me to answer in more detail? For example, are you interested in its geology, atmosphere, history, or something else?",
        additional_kwargs={},
        response_metadata={},
    ),
]


user_input = "Shorten the explanation of Earth."
prompt = chat_template.invoke({"chat_history": chat_history, "query": user_input})

print(prompt)
